# Description: Configuration file for the aeroelastic environment
# Physical parameters
m: 3. # mass of the wing
xf: 0.0375  # distance from the the leading edge to the pitch axis
c: 0.15 # chord length
xh: 0.1125 # distance from the leading edge to the hinge  
kh: 200 #  stiffness
kalpha: 4 #  torsional stiffness wing
rho: 1.225 # air density
U: 12 # flow velocity
t_max: 10.0 # time span
span: 0.45 # span of the wing
f_actuation: 50. # actuation frequency
dt_computation: 0.005 # time step for the ODE resolution

#Initial conditions
initial_condition_type: 'h' # 'h', 'alpha' or'beta'
h0: [0.030,0.030] # initial z position  range       
alpha0: [-0.05,0.05] # initial angle of attack range
beta0: [-0.05,0.05] # initial deflection angle range

#Reward function 
reward_function : 'energy_flap' # energy_no_flap or h_position


